import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Documentation',
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
  ],
};

export default sidebars;


